services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appointment_scheduler
    volumes:
      - .:/var/www
    depends_on:
      - redis
    networks:
      - appointment_scheduler

  nginx:
    image: nginx:alpine
    container_name: appointment_scheduler_nginx
    ports:
      - "9999:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - appointment_scheduler

  redis:
    image: redis:alpine
    container_name: laravel_redis
    networks:
      - appointment_scheduler

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_queue
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    depends_on:
      - app
      - redis
    networks:
      - appointment_scheduler

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_scheduler
    command: |
      sh -c "while true; do php artisan schedule:run; sleep 60; done"
    depends_on:
      - app
    networks:
      - appointment_scheduler

networks:
  appointment_scheduler:
    driver: bridge
